### ISSUE TITLE
我嘗試了LE版

### ISSUE THREAD

**Issue by XingSkyrim** [Yu5h1/ArmorEspGenerator#2]
連讀取都無法XD lodding出現會直接CTD 我會在discord傳給你我的測試ESP

**Comment by Yu5h1** [comment]
> 連讀取都無法XD lodding出現會直接CTD 我會在discord傳給你我的測試ESP

瞭解

**Comment by XingSkyrim** [comment]
我發現原因
LE是因為前置heelssound.ESP沒放在DATA裡面所以CTD
這回報太菜了 我的錯 抱歉

**Comment by xingdagg666** [comment]
我發現原因
LE是因為前置heelssound.ESP沒放在DATA裡面所以CTD
這回報太菜了 我的錯 抱歉

**Comment by XingSkyrim** [comment]
中秋快樂YU大
有幾點想回報:
1.armor addon可以讀的到網格裡面的順序 但armor似乎不行 而且希望能跟著armor addon 的3dindex 的順序一樣 這樣不欲再做一次重複設定XD

2.texture set裡面的其他貼圖例如norma法線這些要另外添加的除了直接把路徑寫上去 似乎就沒有其他方法 
因為右鍵點開 名稱 也只是打開視窗跳出資料夾而已 所以我在想 是否可以讓法線貼圖 這些主要跟改色貼圖的主貼圖不同 不需要更改的 能直接讀取網格裡面的texture set 一起生成

3.這個問題需要舉例 你可以試試我上次傳給你的那套 當已經添加BW1的texture set後 再添加BW2的texture set時 EditorID 會與BW1重複一樣  所以我在想這種情形能否用降冪或升冪方式 命名來避免重複呢

有空再麻煩妳解決了 1目前比較希望能先解決 2.3就比較不急
再祝中秋愉快

**Comment by Yu5h1** [comment]
OK
