### ISSUE TITLE
感謝YU 只是有個小問題

### ISSUE THREAD

**Issue by XingSkyrim** [Yu5h1/ArmorEspGenerator#3]
感謝YU大的更新 我目前測試都運行良好
只是有個額外小問題  我有次嘗試再外面用筆電使用時 打開程式後就會直接CTD
會是我有少安裝甚麼前置要求嗎?
抱歉這回報很奇怪XD 我PC上都用得很好 我只是想回報有個在筆電上使用直接CTD的情形

**Comment by Yu5h1** [comment]
OK 我再檢查看看
